### ISSUE TITLE
manifest.json invalid in Firefox.

### ISSUE THREAD

**Issue by GattN1** [leepa/aws-simple-iconification-service#2]
Firefox requires manifest.json to contain:

`"applications": {
    "gecko": {
       "id": "YOURID@HERE"
    }
}`

However, this breaks the extension in Chrome.

**Comment by leepa** [comment]
The manifest is fine with Firefox - as shown by it being on the Addons site for Mozilla Firefox.

**Comment by GattN1** [comment]
![image](https://user-images.githubusercontent.com/61706367/75708050-e4095500-5c74-11ea-94d6-f6a610517bdb.png)
